# Commented out temporarily

# stages:
# - setup
# - build

# setup windows:
#   stage: setup
#   tags:
#     - windows
#   script:
#     # TODO: Work out how to get MSYS 2, CMake and Qt 5
#     - choco install qt5

# setup linux:
#   stage: setup
#   tags:
#     - docker
#   image: ubuntu:latest
#   script:
#     # TODO: Do I need sudo
#     - apt-get update
#     - apt-get install build-essential
#     - apt-get install cmake
#     - apt-get install qt5-default

# build windows:
#   stage: build
#   tags:
#     - windows
#   script:
#     - mkdir build
#     - cd build
#     - cmake -G "MSYS Makefiles" ..
#     # TODO: Use "make install"
#     - make
#   artifacts:
#     paths:
#       - install/

# build linux:
#   stage: build
#   tags:
#     docker
#   image: ubuntu:latest
#   script:
#     - mkdir build
#     - cd build
#     - cmake ..
#     # TODO: Use "make install"
#     - make
#   artifacts:
#     paths:
#       - install/
